### ISSUE TITLE
Semi-random backstitch connection to previous backstitch

### ISSUE THREAD

**Issue by WallK** [embroidery-space/embroidery-studio#50]
Backstitch is continuing from previous close backstitch if first click is not in the corner (intermittent)

#### STR:
1. Create couple backstitches by dragging
2. Try to create some more by dragging nearby

**ER:** New backstitch is created from the drag start point
**AR:** New backstitch is connected to the old one with a long straight stitch

#### Screen recording:
![embroidery-studio_Z4LHsMwvoh](https://github.com/user-attachments/assets/b5032551-5279-4b9b-9b6a-d5ca26d350e2)

**Comment by niusia-ua** [comment]
Resolved in https://github.com/embroidery-space/embroidery-studio/pull/58/commits/db50b99c39f01b877adfc886761c71ec5415df88
