### ISSUE TITLE
Can't use first color in palette

### ISSUE THREAD

**Issue by WallK** [embroidery-space/embroidery-studio#60]
With first color selected stitches are not placed on canvas
Second and other colors are working

STR:
Create new pattern
Add color to palette
Try to add some full stitches

ER:
Stitches appear on a pattern

AR:
Nothing is added to a pattern

![embroidery-studio_IwKs3yV5GE](https://github.com/user-attachments/assets/c9b3e2c7-192f-49cc-a75e-d13803b8cdb1)

**Comment by niusia-ua** [comment]
Resolved in https://github.com/embroidery-space/embroidery-studio/pull/58/commits/db50b99c39f01b877adfc886761c71ec5415df88
